// ---------------------------------------------------------------------------
// Mock data — replace with real API calls when connecting a backend
// ---------------------------------------------------------------------------
import type { FarmerRequest, FulfillmentRequest } from "./types";

export const MOCK_REQUESTS: FarmerRequest[] = [
  {
    id: "FS-2024-001", date: "12 Jan 2024", agent: "Kofi Mensah", community: "Tamale Metro",
    groupName: "Savannah Growers Union", score: null, stage: "synced", farmers: 22,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: null,
    groupScore: 65,
    farmersList: [
      { id: "FRM-0011", name: "Abena Owusu" },
      { id: "FRM-0012", name: "Kweku Asante" },
      { id: "FRM-0013", name: "Adwoa Mensah" },
      { id: "FRM-0014", name: "Kofi Adu" },
      { id: "FRM-0015", name: "Akosua Baidoo" },
      { id: "FRM-0016", name: "Yaw Appiah" },
      { id: "FRM-0017", name: "Efua Darko" },
      { id: "FRM-0018", name: "Nana Boateng" },
    ],
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0244-567-890", momoName: "Savannah Union GH" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.5 },
    ],
  },
  {
    id: "FS-2024-002", date: "15 Jan 2024", agent: "Ama Owusu", community: "Sawla-Tuna-Kalba",
    groupName: "Northern Fields Cooperative", score: null, stage: "synced", farmers: 18,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: null,
    hasFinancialRecords: true,
    groupScore: 48,
    farmersList: [
      { id: "FRM-0021", name: "Issaka Mahama" },
      { id: "FRM-0022", name: "Ramatu Abubakari" },
      { id: "FRM-0023", name: "Sumaila Seidu" },
      { id: "FRM-0024", name: "Fatima Yakubu" },
      { id: "FRM-0025", name: "Alhassan Fuseini" },
      { id: "FRM-0026", name: "Zenabu Dauda" },
    ],
    supportInterests: [
      { rank: "Primary",   type: "Ploughing", landSizePerFarmer: 2.0 },
      { rank: "Secondary", type: "Cash",      amountPerFarmer: 100, momoNumber: "0200-123-456", momoName: "Northern Coop" },
    ],
  },
  {
    id: "FS-2024-013", date: "08 Feb 2024", agent: "Kofi Mensah", community: "Nkoranza",
    groupName: "Nkoranza Double Yield Group", score: 72, stage: "pending_approval", farmers: 18,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: null,
    wantsDouble: true,
    supportInterests: [
      { rank: "Primary", type: "Cash", amountPerFarmer: 120, momoNumber: "0244-321-654", momoName: "Nkoranza DY Group" },
    ],
    actionHistory: [
      { id: "013-1", stage: "synced", actor: "Kofi Mensah", action: "Scored request — 72%", timestamp: "07 Feb 2024, 14:30" },
    ],
  },
  {
    id: "FS-2024-003", date: "18 Jan 2024", agent: "Yaw Darko", community: "Bole",
    groupName: "Bole Farmers Alliance", score: 62, stage: "pending_approval", farmers: 14,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: null,
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 150, momoNumber: "0551-234-567", momoName: "Bole Alliance" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.0 },
    ],
    actionHistory: [
      { id: "003-1", stage: "synced", actor: "Yaw Darko", action: "Scored request — 62%", timestamp: "17 Jan 2024, 10:00" },
    ],
  },
  {
    id: "FS-2024-004", date: "20 Jan 2024", agent: "Abena Asante", community: "Wa East",
    groupName: "Wa East Crop Circle", score: 78, stage: "pending_approval", farmers: 31,
    onHold: true, holdComment: "MoMo account details need verification from field.", rejectionComment: "", approvedSupportType: null,
    supportInterests: [
      { rank: "Primary",   type: "Ploughing", landSizePerFarmer: 3.0 },
      { rank: "Secondary", type: "Cash",      amountPerFarmer: 200, momoNumber: "0244-987-654", momoName: "WE Crop Circle" },
    ],
    actionHistory: [
      { id: "004-1", stage: "synced", actor: "Abena Asante", action: "Scored request — 78%", timestamp: "19 Jan 2024, 09:15" },
      { id: "004-2", stage: "pending_approval", actor: "Abena Asante", action: "Placed on hold", reason: "MoMo account details need verification from field.", timestamp: "20 Jan 2024, 11:00" },
    ],
  },
  {
    id: "FS-2024-005", date: "10 Jan 2024", agent: "Kwame Boateng", community: "Tamale Metro",
    groupName: "Metro Harvest Group", score: 38, stage: "rejected", farmers: 9,
    onHold: false, holdComment: "", rejectionComment: "Score too low to meet minimum eligibility threshold of 50.", approvedSupportType: null,
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 80,  momoNumber: "0200-000-001", momoName: "Metro Harvest" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 0.5 },
    ],
    actionHistory: [
      { id: "005-1", stage: "synced", actor: "Kwame Boateng", action: "Scored request — 38%", timestamp: "09 Jan 2024, 15:00" },
      { id: "005-2", stage: "pending_approval", actor: "Kwame Boateng", action: "Rejected — score below minimum threshold", reason: "Score too low to meet minimum eligibility threshold of 50.", timestamp: "10 Jan 2024, 09:30" },
    ],
  },
  {
    id: "FS-2024-006", date: "22 Jan 2024", agent: "Efua Nkrumah", community: "Sawla-Tuna-Kalba",
    groupName: "Kalba Green Initiative", score: 84, stage: "agent_confirmation", farmers: 27,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0244-111-222", momoName: "Kalba Green" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.5 },
    ],
    actionHistory: [
      { id: "006-1", stage: "synced", actor: "Efua Nkrumah", action: "Scored request — 84%", timestamp: "21 Jan 2024, 13:00" },
      { id: "006-2", stage: "pending_approval", actor: "Efua Nkrumah", action: "Approved for Cash support — GHS 120 per farmer", timestamp: "22 Jan 2024, 10:15" },
    ],
  },
  {
    id: "FS-2024-007", date: "25 Jan 2024", agent: "Nana Adjei", community: "Bole",
    groupName: "Bole Plough Collective", score: 91, stage: "finance_disbursement", farmers: 16,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedLandSizePerFarmer: 2.0,
    momoNumber: "0551-777-888", momoName: "Bole Collective",
    supportInterests: [
      { rank: "Primary",   type: "Ploughing", landSizePerFarmer: 2.0 },
      { rank: "Secondary", type: "Cash",      amountPerFarmer: 180, momoNumber: "0551-777-888", momoName: "Bole Collective" },
    ],
    actionHistory: [
      { id: "007-1", stage: "synced", actor: "Nana Adjei", action: "Scored request — 91%", timestamp: "24 Jan 2024, 11:00" },
      { id: "007-2", stage: "pending_approval", actor: "Nana Adjei", action: "Approved for Ploughing support — 2.0 ac per farmer", timestamp: "25 Jan 2024, 09:00" },
      { id: "007-3", stage: "agent_confirmation", actor: "Nana Adjei", action: "Confirmed participating farmers and MoMo account (0551-777-888)", timestamp: "26 Jan 2024, 08:30" },
    ],
  },
  {
    id: "FS-2024-009", date: "26 Jan 2024", agent: "Kofi Mensah", community: "Tamale Metro",
    groupName: "Tamale Pioneer Farmers", score: 75, stage: "finance_disbursement", farmers: 20,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 150,
    momoNumber: "0244-333-444", momoName: "Tamale Pioneer",
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 150, momoNumber: "0244-333-444", momoName: "Tamale Pioneer" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.2 },
    ],
    actionHistory: [
      { id: "009-1", stage: "synced", actor: "Kofi Mensah", action: "Scored request — 75%", timestamp: "25 Jan 2024, 14:00" },
      { id: "009-2", stage: "pending_approval", actor: "Kofi Mensah", action: "Approved for Cash support — GHS 150 per farmer", timestamp: "26 Jan 2024, 10:00" },
      { id: "009-3", stage: "agent_confirmation", actor: "Kofi Mensah", action: "Confirmed participating farmers and MoMo account (0244-333-444)", timestamp: "27 Jan 2024, 09:00" },
    ],
  },
  {
    id: "FS-2024-008", date: "30 Jan 2024", agent: "Akosua Frimpong", community: "Tamale Metro",
    groupName: "Metro Food Security Group", score: 88, stage: "disbursed", farmers: 34,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0244-555-666", momoName: "Metro Food Security",
    transactionId: "TXN-4F8A2B1C", disbursedAmount: 4080, disbursedDate: "30 Jan 2024",
    disbursementBreakdown: { baseAmount: 4080, withdrawalCharge: 0, transportAllowance: 0, total: 4080 },
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0244-555-666", momoName: "Metro Food Security" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.0 },
    ],
    actionHistory: [
      { id: "008-1", stage: "synced",               actor: "Douglas Gockah", action: "Scored request — 88%",                                                            timestamp: "28 Jan 2024, 09:15" },
      { id: "008-2", stage: "pending_approval",      actor: "Douglas Gockah", action: "Approved for Cash support — GHS 120 per farmer",                                 timestamp: "28 Jan 2024, 10:42" },
      { id: "008-3", stage: "agent_confirmation",    actor: "Douglas Gockah", action: "Confirmed participating farmers and MoMo account (0244-555-666)",                timestamp: "29 Jan 2024, 08:30" },
      { id: "008-4", stage: "finance_disbursement",  actor: "Douglas Gockah", action: "Disbursed GHS 4,080 via MoMo · TXN-4F8A2B1C",                                  timestamp: "30 Jan 2024, 11:00" },
    ],
  },
  {
    id: "FS-2024-010", date: "28 Jan 2024", agent: "Ama Owusu", community: "Wa East",
    groupName: "Wa East Food Coalition", score: 95, stage: "disbursed", farmers: 40,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 180,
    momoNumber: "0244-999-000", momoName: "WE Food Coalition",
    transactionId: "TXN-7C3D9E2A", disbursedAmount: 7250, disbursedDate: "28 Jan 2024",
    disbursementBreakdown: { baseAmount: 7200, withdrawalCharge: 20, transportAllowance: 30, total: 7250 },
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 180, momoNumber: "0244-999-000", momoName: "WE Food Coalition" },
    ],
    actionHistory: [
      { id: "010-1", stage: "synced",               actor: "Douglas Gockah", action: "Scored request — 95%",                                                            timestamp: "25 Jan 2024, 14:05" },
      { id: "010-2", stage: "pending_approval",      actor: "Douglas Gockah", action: "Updated cash amount per farmer from GHS 150 to GHS 180", reason: "Revised upward to match prevailing market rate for the season", timestamp: "26 Jan 2024, 09:20" },
      { id: "010-3", stage: "pending_approval",      actor: "Douglas Gockah", action: "Approved for Cash support — GHS 180 per farmer",                                 timestamp: "26 Jan 2024, 09:35" },
      { id: "010-4", stage: "agent_confirmation",    actor: "Douglas Gockah", action: "Confirmed participating farmers and MoMo account (0244-999-000)",                timestamp: "27 Jan 2024, 10:00" },
      { id: "010-5", stage: "finance_disbursement",  actor: "Douglas Gockah", action: "Disbursed GHS 7,250 via MoMo · TXN-7C3D9E2A",                                  timestamp: "28 Jan 2024, 13:22" },
    ],
  },
  {
    id: "FS-2024-014", date: "01 Feb 2024", agent: "Yaw Darko", community: "Nanumba North",
    groupName: "Nanumba Agri Group", score: 80, stage: "disbursed", farmers: 19,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 150,
    momoNumber: "0246-601-432", momoName: "Nanumba Agri Group",
    transactionId: "TXN-2B4E6A8C", disbursedAmount: 2900, disbursedDate: "01 Feb 2024",
    disbursementBreakdown: { baseAmount: 2850, withdrawalCharge: 0, transportAllowance: 50, total: 2900 },
    supportInterests: [
      { rank: "Primary", type: "Cash", amountPerFarmer: 150, momoNumber: "0246-601-432", momoName: "Nanumba Agri Group" },
    ],
    actionHistory: [
      { id: "014-1", stage: "synced",               actor: "Douglas Gockah", action: "Scored request — 80%",                                                            timestamp: "29 Jan 2024, 11:00" },
      { id: "014-2", stage: "pending_approval",      actor: "Douglas Gockah", action: "Approved for Cash support — GHS 150 per farmer",                                 timestamp: "30 Jan 2024, 09:10" },
      { id: "014-3", stage: "agent_confirmation",    actor: "Douglas Gockah", action: "Confirmed participating farmers and MoMo account (0246-601-432)",                timestamp: "31 Jan 2024, 08:45" },
      { id: "014-4", stage: "finance_disbursement",  actor: "Douglas Gockah", action: "Disbursed GHS 2,900 via MoMo · TXN-2B4E6A8C",                                  timestamp: "01 Feb 2024, 10:30" },
    ],
  },
  {
    id: "FS-2024-015", date: "03 Feb 2024", agent: "Nana Adjei", community: "Tolon",
    groupName: "Tolon Cooperative Society", score: 87, stage: "disbursed", farmers: 28,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0551-882-015", momoName: "Tolon Coop Society",
    transactionId: "TXN-9D1F3H5J", disbursedAmount: 3380, disbursedDate: "03 Feb 2024",
    disbursementBreakdown: { baseAmount: 3360, withdrawalCharge: 20, transportAllowance: 0, total: 3380 },
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0551-882-015", momoName: "Tolon Coop Society" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.5 },
    ],
    actionHistory: [
      { id: "015-1", stage: "synced",               actor: "Douglas Gockah", action: "Scored request — 87%",                                                            timestamp: "01 Feb 2024, 09:00" },
      { id: "015-2", stage: "pending_approval",      actor: "Douglas Gockah", action: "Approved for Cash support — GHS 120 per farmer",                                 timestamp: "01 Feb 2024, 11:30" },
      { id: "015-3", stage: "agent_confirmation",    actor: "Douglas Gockah", action: "Confirmed participating farmers and MoMo account (0551-882-015)",                timestamp: "02 Feb 2024, 09:15" },
      { id: "015-4", stage: "finance_disbursement",  actor: "Douglas Gockah", action: "Disbursed GHS 3,380 via MoMo · TXN-9D1F3H5J",                                  timestamp: "03 Feb 2024, 10:05" },
    ],
  },
  {
    id: "FS-2024-011", date: "02 Feb 2024", agent: "Akosua Frimpong", community: "Tamale Metro",
    groupName: "Metro Pioneer Group", score: 80, stage: "opted_out", farmers: 25,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0244-777-888", momoName: "Metro Pioneer",
    transactionId: "TXN-1A2B3C4D", disbursedAmount: 2640, disbursedDate: "02 Feb 2024",
    optedOutFarmers: ["Rabi Alhassan", "Sana Korawuni", "Azuma Atta", "Doapok Tidow", "Mercy Bakanyin"],
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0244-777-888", momoName: "Metro Pioneer" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.0 },
    ],
  },
  {
    id: "FS-2024-012", date: "05 Feb 2024", agent: "Yaw Darko", community: "Bole",
    groupName: "Bole United Farmers", score: 88, stage: "opted_out", farmers: 30,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 150,
    momoNumber: "0551-444-555", momoName: "Bole United",
    transactionId: "TXN-5E6F7G8H", disbursedAmount: 4200, disbursedDate: "05 Feb 2024",
    optedOutFarmers: ["Kusohuba Duku", "Shetu Affuro", "Yetama Akuta"],
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 150, momoNumber: "0551-444-555", momoName: "Bole United" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.5 },
    ],
  },

  // ── Extra disbursed records (for table pagination) ──────────────────────
  {
    id: "FS-2024-016", date: "06 Feb 2024", agent: "Kofi Mensah", community: "Kumbungu",
    groupName: "Kumbungu Crop Growers", score: 74, stage: "disbursed", farmers: 21,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 130,
    momoNumber: "0244-101-202", momoName: "Kumbungu Crop Growers",
    transactionId: "TXN-A1B2C3D4", disbursedAmount: 2730, disbursedDate: "06 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 130, momoNumber: "0244-101-202", momoName: "Kumbungu Crop Growers" }],
  },
  {
    id: "FS-2024-017", date: "07 Feb 2024", agent: "Ama Owusu", community: "Savelugu",
    groupName: "Savelugu Women Farmers", score: 83, stage: "disbursed", farmers: 16,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 150,
    momoNumber: "0200-303-404", momoName: "Savelugu Women Farmers",
    transactionId: "TXN-E5F6G7H8", disbursedAmount: 2400, disbursedDate: "07 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 150, momoNumber: "0200-303-404", momoName: "Savelugu Women Farmers" }],
  },
  {
    id: "FS-2024-018", date: "08 Feb 2024", agent: "Yaw Darko", community: "Karaga",
    groupName: "Karaga Seedlings Collective", score: 69, stage: "disbursed", farmers: 12,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedAmountPerFarmer: null,
    approvedLandSizePerFarmer: 2.0,
    momoNumber: "0551-505-606", momoName: "Karaga Seedlings",
    transactionId: "TXN-I9J0K1L2", disbursedAmount: 1560, disbursedDate: "08 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Ploughing", landSizePerFarmer: 2.0 }],
  },
  {
    id: "FS-2024-019", date: "09 Feb 2024", agent: "Nana Adjei", community: "Zabzugu",
    groupName: "Zabzugu Agri Pioneers", score: 91, stage: "disbursed", farmers: 37,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 200,
    momoNumber: "0244-707-808", momoName: "Zabzugu Agri Pioneers",
    transactionId: "TXN-M3N4O5P6", disbursedAmount: 7400, disbursedDate: "09 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 200, momoNumber: "0244-707-808", momoName: "Zabzugu Agri Pioneers" }],
  },
  {
    id: "FS-2024-020", date: "10 Feb 2024", agent: "Akosua Frimpong", community: "Gushegu",
    groupName: "Gushegu Yield Alliance", score: 78, stage: "disbursed", farmers: 29,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 110,
    momoNumber: "0246-909-010", momoName: "Gushegu Yield Alliance",
    transactionId: "TXN-Q7R8S9T0", disbursedAmount: 3190, disbursedDate: "10 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 110, momoNumber: "0246-909-010", momoName: "Gushegu Yield Alliance" }],
  },
  {
    id: "FS-2024-021", date: "11 Feb 2024", agent: "Kofi Mensah", community: "Nanton",
    groupName: "Nanton Food Bank Growers", score: 85, stage: "disbursed", farmers: 23,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 140,
    momoNumber: "0244-111-222", momoName: "Nanton Food Bank",
    transactionId: "TXN-U1V2W3X4", disbursedAmount: 3220, disbursedDate: "11 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 140, momoNumber: "0244-111-222", momoName: "Nanton Food Bank" }],
  },
  {
    id: "FS-2024-022", date: "12 Feb 2024", agent: "Ama Owusu", community: "Mion",
    groupName: "Mion Cooperative Farmers", score: 66, stage: "disbursed", farmers: 18,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedAmountPerFarmer: null,
    approvedLandSizePerFarmer: 1.5,
    momoNumber: "0200-333-444", momoName: "Mion Coop Farmers",
    transactionId: "TXN-Y5Z6A7B8", disbursedAmount: 1800, disbursedDate: "12 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Ploughing", landSizePerFarmer: 1.5 }],
  },
  {
    id: "FS-2024-023", date: "13 Feb 2024", agent: "Yaw Darko", community: "Chereponi",
    groupName: "Chereponi Upland Farmers", score: 72, stage: "disbursed", farmers: 15,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0551-555-666", momoName: "Chereponi Upland",
    transactionId: "TXN-C9D0E1F2", disbursedAmount: 1800, disbursedDate: "13 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 120, momoNumber: "0551-555-666", momoName: "Chereponi Upland" }],
  },
  {
    id: "FS-2024-024", date: "14 Feb 2024", agent: "Nana Adjei", community: "Bunkpurugu",
    groupName: "Bunkpurugu Harvest Group", score: 89, stage: "disbursed", farmers: 32,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 160,
    momoNumber: "0244-777-888", momoName: "Bunkpurugu Harvest",
    transactionId: "TXN-G3H4I5J6", disbursedAmount: 5120, disbursedDate: "14 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 160, momoNumber: "0244-777-888", momoName: "Bunkpurugu Harvest" }],
  },
  {
    id: "FS-2024-025", date: "15 Feb 2024", agent: "Akosua Frimpong", community: "Yunyoo",
    groupName: "Yunyoo Valley Growers", score: 77, stage: "disbursed", farmers: 20,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 175,
    momoNumber: "0246-999-000", momoName: "Yunyoo Valley Growers",
    transactionId: "TXN-K7L8M9N0", disbursedAmount: 3500, disbursedDate: "15 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 175, momoNumber: "0246-999-000", momoName: "Yunyoo Valley Growers" }],
  },
  {
    id: "FS-2024-026", date: "16 Feb 2024", agent: "Kofi Mensah", community: "Tatale-Sanguli",
    groupName: "Tatale Organic Farmers", score: 82, stage: "disbursed", farmers: 26,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 130,
    momoNumber: "0244-121-131", momoName: "Tatale Organic Farmers",
    transactionId: "TXN-O1P2Q3R4", disbursedAmount: 3380, disbursedDate: "16 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 130, momoNumber: "0244-121-131", momoName: "Tatale Organic Farmers" }],
  },
  {
    id: "FS-2024-027", date: "17 Feb 2024", agent: "Ama Owusu", community: "Walewale",
    groupName: "Walewale Grain Collective", score: 93, stage: "disbursed", farmers: 45,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 190,
    momoNumber: "0200-141-151", momoName: "Walewale Grain Collective",
    transactionId: "TXN-S5T6U7V8", disbursedAmount: 8550, disbursedDate: "17 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 190, momoNumber: "0200-141-151", momoName: "Walewale Grain Collective" }],
  },
  {
    id: "FS-2024-028", date: "18 Feb 2024", agent: "Yaw Darko", community: "Builsa North",
    groupName: "Builsa North Farmers Union", score: 70, stage: "disbursed", farmers: 22,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedAmountPerFarmer: null,
    approvedLandSizePerFarmer: 1.8,
    momoNumber: "0551-161-171", momoName: "Builsa North Union",
    transactionId: "TXN-W9X0Y1Z2", disbursedAmount: 2640, disbursedDate: "18 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Ploughing", landSizePerFarmer: 1.8 }],
  },
  {
    id: "FS-2024-029", date: "19 Feb 2024", agent: "Nana Adjei", community: "Kasena-Nankana",
    groupName: "Kasena Irrigation Collective", score: 86, stage: "disbursed", farmers: 31,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 145,
    momoNumber: "0244-181-191", momoName: "Kasena Irrigation Collective",
    transactionId: "TXN-A3B4C5D6", disbursedAmount: 4495, disbursedDate: "19 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 145, momoNumber: "0244-181-191", momoName: "Kasena Irrigation Collective" }],
  },
  {
    id: "FS-2024-030", date: "20 Feb 2024", agent: "Akosua Frimpong", community: "Sissala East",
    groupName: "Sissala Dryland Farmers", score: 75, stage: "disbursed", farmers: 17,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0246-201-211", momoName: "Sissala Dryland Farmers",
    transactionId: "TXN-E7F8G9H0", disbursedAmount: 2040, disbursedDate: "20 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 120, momoNumber: "0246-201-211", momoName: "Sissala Dryland Farmers" }],
  },
  {
    id: "FS-2024-031", date: "21 Feb 2024", agent: "Kofi Mensah", community: "Jirapa",
    groupName: "Jirapa Hills Cooperative", score: 88, stage: "disbursed", farmers: 38,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 155,
    momoNumber: "0244-221-231", momoName: "Jirapa Hills Cooperative",
    transactionId: "TXN-I1J2K3L4", disbursedAmount: 5890, disbursedDate: "21 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 155, momoNumber: "0244-221-231", momoName: "Jirapa Hills Cooperative" }],
  },
  {
    id: "FS-2024-032", date: "22 Feb 2024", agent: "Ama Owusu", community: "Lawra",
    groupName: "Lawra River Farmers", score: 79, stage: "disbursed", farmers: 24,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 135,
    momoNumber: "0200-241-251", momoName: "Lawra River Farmers",
    transactionId: "TXN-M5N6O7P8", disbursedAmount: 3240, disbursedDate: "22 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 135, momoNumber: "0200-241-251", momoName: "Lawra River Farmers" }],
  },
  {
    id: "FS-2024-033", date: "23 Feb 2024", agent: "Yaw Darko", community: "Nandom",
    groupName: "Nandom Plateau Growers", score: 81, stage: "disbursed", farmers: 27,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedAmountPerFarmer: null,
    approvedLandSizePerFarmer: 2.2,
    momoNumber: "0551-261-271", momoName: "Nandom Plateau Growers",
    transactionId: "TXN-Q9R0S1T2", disbursedAmount: 3510, disbursedDate: "23 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Ploughing", landSizePerFarmer: 2.2 }],
  },
  {
    id: "FS-2024-034", date: "24 Feb 2024", agent: "Nana Adjei", community: "Daffiama-Bussie",
    groupName: "Daffiama United Growers", score: 90, stage: "disbursed", farmers: 33,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 170,
    momoNumber: "0244-281-291", momoName: "Daffiama United Growers",
    transactionId: "TXN-U3V4W5X6", disbursedAmount: 5610, disbursedDate: "24 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 170, momoNumber: "0244-281-291", momoName: "Daffiama United Growers" }],
  },
  {
    id: "FS-2024-035", date: "25 Feb 2024", agent: "Akosua Frimpong", community: "Nadowli-Kaleo",
    groupName: "Kaleo Lowland Farmers", score: 73, stage: "disbursed", farmers: 19,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 125,
    momoNumber: "0246-301-311", momoName: "Kaleo Lowland Farmers",
    transactionId: "TXN-Y7Z8A9B0", disbursedAmount: 2375, disbursedDate: "25 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 125, momoNumber: "0246-301-311", momoName: "Kaleo Lowland Farmers" }],
  },
];

// ---------------------------------------------------------------------------
// Support Fulfilment mock data
// Mirrors disbursed groups, tracking per-farmer receipt of funds.
// ---------------------------------------------------------------------------
export const MOCK_FULFILLMENT_REQUESTS: FulfillmentRequest[] = [
  // ── Pending Fulfilment ──────────────────────────────────────────────────
  {
    id: "FS-2024-008",
    groupName: "Metro Food Security Group",
    community: "Tamale Metro",
    agent: "Akosua Frimpong",
    disbursedDate: "30 Jan 2024",
    transactionId: "TXN-4F8A2B1C",
    disbursedAmount: 4080,
    approvedAmountPerFarmer: 120,
    approvedSupportType: "Cash",
    fulfillmentStage: "pending_fulfillment",
    momoNumber: "0244-555-666",
    momoName: "Metro Food Security",
    confirmedFarmers: [
      { id: "F001", name: "Ama Mensah",       received: false },
      { id: "F002", name: "Kofi Asante",      received: false },
      { id: "F003", name: "Akua Boateng",     received: false },
      { id: "F004", name: "Yaw Amoah",        received: false },
      { id: "F005", name: "Abena Darko",      received: false },
      { id: "F006", name: "Kwame Appiah",     received: false },
      { id: "F007", name: "Adwoa Acheampong", received: false },
      { id: "F008", name: "Kwesi Ofori",      received: false },
      { id: "F009", name: "Afua Frimpong",    received: false },
      { id: "F010", name: "Kojo Adjei",       received: false },
      { id: "F011", name: "Akosua Asare",     received: false },
      { id: "F012", name: "Nana Boakye",      received: false },
      { id: "F013", name: "Efua Antwi",       received: false },
      { id: "F014", name: "Ato Nyarko",       received: false },
      { id: "F015", name: "Maama Bediako",    received: false },
      { id: "F016", name: "Yaa Agyei",        received: false },
      { id: "F017", name: "Kwabena Opoku",    received: false },
      { id: "F018", name: "Adjoa Adusei",     received: false },
      { id: "F019", name: "Kofi Kwarteng",    received: false },
      { id: "F020", name: "Esi Mensah",       received: false },
      { id: "F021", name: "Akua Owusu",       received: false },
      { id: "F022", name: "Yaw Darko",        received: false },
      { id: "F023", name: "Kwame Asante",     received: false },
      { id: "F024", name: "Abena Boateng",    received: false },
      { id: "F025", name: "Kwesi Amoah",      received: false },
      { id: "F026", name: "Adwoa Frimpong",   received: false },
      { id: "F027", name: "Kojo Appiah",      received: false },
      { id: "F028", name: "Akosua Adjei",     received: false },
      { id: "F029", name: "Nana Asare",       received: false },
      { id: "F030", name: "Efua Boakye",      received: false },
      { id: "F031", name: "Ato Antwi",        received: false },
      { id: "F032", name: "Maama Nyarko",     received: false },
      { id: "F033", name: "Yaa Bediako",      received: false },
      { id: "F034", name: "Kwabena Agyei",    received: false },
    ],
  },
  {
    id: "FS-2024-010",
    groupName: "Wa East Food Coalition",
    community: "Wa East",
    agent: "Ama Owusu",
    disbursedDate: "28 Jan 2024",
    transactionId: "TXN-7C3D9E2A",
    disbursedAmount: 7200,
    approvedAmountPerFarmer: 180,
    approvedSupportType: "Cash",
    fulfillmentStage: "pending_fulfillment",
    momoNumber: "0244-999-000",
    momoName: "WE Food Coalition",
    confirmedFarmers: [
      { id: "G001", name: "Issaka Mahama",      received: false },
      { id: "G002", name: "Ramatu Abubakari",   received: false },
      { id: "G003", name: "Sumaila Seidu",      received: false },
      { id: "G004", name: "Fatima Yakubu",      received: false },
      { id: "G005", name: "Alhassan Fuseini",   received: false },
      { id: "G006", name: "Zenabu Dauda",       received: false },
      { id: "G007", name: "Amadu Mahama",       received: false },
      { id: "G008", name: "Bintu Seidu",        received: false },
      { id: "G009", name: "Hawa Yakubu",        received: false },
      { id: "G010", name: "Safiatu Alhassan",   received: false },
      { id: "G011", name: "Mariama Dauda",      received: false },
      { id: "G012", name: "Fatimatu Amadu",     received: false },
      { id: "G013", name: "Huseini Baba",       received: false },
      { id: "G014", name: "Baba Mahama",        received: false },
      { id: "G015", name: "Issaka Seidu",       received: false },
      { id: "G016", name: "Ramatu Yakubu",      received: false },
      { id: "G017", name: "Sumaila Alhassan",   received: false },
      { id: "G018", name: "Fatima Dauda",       received: false },
      { id: "G019", name: "Alhassan Amadu",     received: false },
      { id: "G020", name: "Zenabu Baba",        received: false },
      { id: "G021", name: "Amadu Seidu",        received: false },
      { id: "G022", name: "Bintu Mahama",       received: false },
      { id: "G023", name: "Hawa Alhassan",      received: false },
      { id: "G024", name: "Safiatu Dauda",      received: false },
      { id: "G025", name: "Mariama Amadu",      received: false },
      { id: "G026", name: "Fatimatu Baba",      received: false },
      { id: "G027", name: "Huseini Mahama",     received: false },
      { id: "G028", name: "Baba Seidu",         received: false },
      { id: "G029", name: "Issaka Alhassan",    received: false },
      { id: "G030", name: "Ramatu Dauda",       received: false },
      { id: "G031", name: "Sumaila Amadu",      received: false },
      { id: "G032", name: "Fatima Baba",        received: false },
      { id: "G033", name: "Alhassan Seidu",     received: false },
      { id: "G034", name: "Zenabu Mahama",      received: false },
      { id: "G035", name: "Amadu Alhassan",     received: false },
      { id: "G036", name: "Bintu Dauda",        received: false },
      { id: "G037", name: "Hawa Amadu",         received: false },
      { id: "G038", name: "Safiatu Baba",       received: false },
      { id: "G039", name: "Mariama Seidu",      received: false },
      { id: "G040", name: "Fatimatu Mahama",    received: false },
    ],
  },

  // ── Partially Fulfilled ─────────────────────────────────────────────────
  {
    id: "FS-2024-014",
    groupName: "Nanumba Agri Group",
    community: "Nanumba North",
    agent: "Yaw Darko",
    disbursedDate: "01 Feb 2024",
    transactionId: "TXN-2B4E6A8C",
    disbursedAmount: 2850,
    approvedAmountPerFarmer: 150,
    approvedSupportType: "Cash",
    fulfillmentStage: "partially_fulfilled",
    momoNumber: "0246-601-432",
    momoName: "Nanumba Agri Group",
    confirmedFarmers: [
      { id: "N001", name: "Sumaila Laar",      received: true,  voiceRecordingDuration: "0:28", receivedDate: "04 Feb 2024" },
      { id: "N002", name: "Fatima Nindow",     received: true,  voiceRecordingDuration: "0:35", receivedDate: "04 Feb 2024" },
      { id: "N003", name: "Alhassan Mahama",   received: true,  voiceRecordingDuration: "0:22", receivedDate: "04 Feb 2024" },
      { id: "N004", name: "Bintu Wuni",        received: true,  voiceRecordingDuration: "0:41", receivedDate: "05 Feb 2024" },
      { id: "N005", name: "Baba Dimari",       received: true,  voiceRecordingDuration: "0:30", receivedDate: "05 Feb 2024" },
      { id: "N006", name: "Issaka Nantomah",   received: true,  voiceRecordingDuration: "0:26", receivedDate: "05 Feb 2024" },
      { id: "N007", name: "Ramatu Zangina",    received: true,  voiceRecordingDuration: "0:33", receivedDate: "06 Feb 2024" },
      { id: "N008", name: "Hawa Nindow",       received: true,  voiceRecordingDuration: "0:19", receivedDate: "06 Feb 2024" },
      { id: "N009", name: "Sumaila Wuni",      received: false },
      { id: "N010", name: "Fatima Dimari",     received: false },
      { id: "N011", name: "Alhassan Zangina",  received: false },
      { id: "N012", name: "Bintu Nantomah",    received: false },
      { id: "N013", name: "Baba Laar",         received: false },
      { id: "N014", name: "Issaka Mahama",     received: false },
      { id: "N015", name: "Ramatu Wuni",       received: false },
      { id: "N016", name: "Hawa Dimari",       received: false },
      { id: "N017", name: "Safiatu Zangina",   received: false },
      { id: "N018", name: "Mariama Nantomah",  received: false },
      { id: "N019", name: "Fatimatu Laar",     received: false },
    ],
    optedOutFarmers: [
      { id: "OPT-N-001", name: "Duni Tichanni" },
      { id: "OPT-N-002", name: "Awabla Bugri"  },
      { id: "OPT-N-003", name: "Asibi Yalpak"  },
    ],
  },
  {
    id: "FS-2024-015",
    groupName: "Tolon Cooperative Society",
    community: "Tolon",
    agent: "Nana Adjei",
    disbursedDate: "03 Feb 2024",
    transactionId: "TXN-9D1F3H5J",
    disbursedAmount: 3360,
    approvedAmountPerFarmer: 120,
    approvedSupportType: "Cash",
    fulfillmentStage: "partially_fulfilled",
    momoNumber: "0551-882-015",
    momoName: "Tolon Coop Society",
    confirmedFarmers: [
      { id: "T001", name: "Ama Seidu",         received: true,  voiceRecordingDuration: "0:31", receivedDate: "06 Feb 2024" },
      { id: "T002", name: "Kofi Mahama",       received: true,  voiceRecordingDuration: "0:27", receivedDate: "06 Feb 2024" },
      { id: "T003", name: "Akua Alhassan",     received: true,  voiceRecordingDuration: "0:38", receivedDate: "06 Feb 2024" },
      { id: "T004", name: "Yaw Dauda",         received: true,  voiceRecordingDuration: "0:24", receivedDate: "07 Feb 2024" },
      { id: "T005", name: "Abena Fuseini",     received: true,  voiceRecordingDuration: "0:29", receivedDate: "07 Feb 2024" },
      { id: "T006", name: "Kwame Tindan",      received: true,  voiceRecordingDuration: "0:32", receivedDate: "07 Feb 2024" },
      { id: "T007", name: "Adwoa Tolon",       received: true,  voiceRecordingDuration: "0:21", receivedDate: "07 Feb 2024" },
      { id: "T008", name: "Kwesi Nantomah",    received: true,  voiceRecordingDuration: "0:35", receivedDate: "08 Feb 2024" },
      { id: "T009", name: "Afua Laar",         received: true,  voiceRecordingDuration: "0:28", receivedDate: "08 Feb 2024" },
      { id: "T010", name: "Kojo Zangina",      received: true,  voiceRecordingDuration: "0:39", receivedDate: "08 Feb 2024" },
      { id: "T011", name: "Akosua Wuni",       received: true,  voiceRecordingDuration: "0:26", receivedDate: "09 Feb 2024" },
      { id: "T012", name: "Nana Dimari",       received: true,  voiceRecordingDuration: "0:33", receivedDate: "09 Feb 2024" },
      { id: "T013", name: "Efua Bawa",         received: true,  voiceRecordingDuration: "0:22", receivedDate: "09 Feb 2024" },
      { id: "T014", name: "Ato Nindow",        received: true,  voiceRecordingDuration: "0:30", receivedDate: "10 Feb 2024" },
      { id: "T015", name: "Maama Baloro",      received: true,  voiceRecordingDuration: "0:25", receivedDate: "10 Feb 2024" },
      { id: "T016", name: "Yaa Seidu",         received: false },
      { id: "T017", name: "Kwabena Mahama",    received: false },
      { id: "T018", name: "Adjoa Alhassan",    received: false },
      { id: "T019", name: "Kofi Dauda",        received: false },
      { id: "T020", name: "Esi Fuseini",       received: false },
      { id: "T021", name: "Kwesi Tindan",      received: false },
      { id: "T022", name: "Araba Tolon",       received: false },
      { id: "T023", name: "Akweley Nantomah",  received: false },
      { id: "T024", name: "Mansa Laar",        received: false },
      { id: "T025", name: "Baaba Zangina",     received: false },
      { id: "T026", name: "Ekua Wuni",         received: false },
      { id: "T027", name: "Naana Dimari",      received: false },
      { id: "T028", name: "Serwaa Bawa",       received: false },
    ],
    optedOutFarmers: [
      { id: "OPT-T-001", name: "Kusohuba Duku"  },
      { id: "OPT-T-002", name: "Mercy Bakanyin" },
    ],
  },

  // ── Fully Fulfilled ─────────────────────────────────────────────────────
  {
    id: "FS-2024-016",
    groupName: "Kumbungu Crop Growers",
    community: "Kumbungu",
    agent: "Kofi Mensah",
    disbursedDate: "06 Feb 2024",
    transactionId: "TXN-A1B2C3D4",
    disbursedAmount: 2730,
    approvedAmountPerFarmer: 130,
    approvedSupportType: "Cash",
    fulfillmentStage: "fully_fulfilled",
    momoNumber: "0244-101-202",
    momoName: "Kumbungu Crop Growers",
    confirmedFarmers: [
      { id: "K001", name: "Ama Kumbungu",    received: true, voiceRecordingDuration: "0:28", receivedDate: "09 Feb 2024" },
      { id: "K002", name: "Kofi Darko",      received: true, voiceRecordingDuration: "0:35", receivedDate: "09 Feb 2024" },
      { id: "K003", name: "Akua Asante",     received: true, voiceRecordingDuration: "0:22", receivedDate: "09 Feb 2024" },
      { id: "K004", name: "Yaw Mensah",      received: true, voiceRecordingDuration: "0:41", receivedDate: "10 Feb 2024" },
      { id: "K005", name: "Abena Owusu",     received: true, voiceRecordingDuration: "0:30", receivedDate: "10 Feb 2024" },
      { id: "K006", name: "Kwame Boateng",   received: true, voiceRecordingDuration: "0:26", receivedDate: "10 Feb 2024" },
      { id: "K007", name: "Adwoa Amoah",     received: true, voiceRecordingDuration: "0:33", receivedDate: "10 Feb 2024" },
      { id: "K008", name: "Kwesi Frimpong",  received: true, voiceRecordingDuration: "0:19", receivedDate: "11 Feb 2024" },
      { id: "K009", name: "Afua Appiah",     received: true, voiceRecordingDuration: "0:36", receivedDate: "11 Feb 2024" },
      { id: "K010", name: "Kojo Acheampong", received: true, voiceRecordingDuration: "0:24", receivedDate: "11 Feb 2024" },
      { id: "K011", name: "Akosua Ofori",    received: true, voiceRecordingDuration: "0:31", receivedDate: "11 Feb 2024" },
      { id: "K012", name: "Nana Adjei",      received: true, voiceRecordingDuration: "0:27", receivedDate: "12 Feb 2024" },
      { id: "K013", name: "Efua Asare",      received: true, voiceRecordingDuration: "0:38", receivedDate: "12 Feb 2024" },
      { id: "K014", name: "Ato Boakye",      received: true, voiceRecordingDuration: "0:29", receivedDate: "12 Feb 2024" },
      { id: "K015", name: "Maama Antwi",     received: true, voiceRecordingDuration: "0:32", receivedDate: "12 Feb 2024" },
      { id: "K016", name: "Yaa Nyarko",      received: true, voiceRecordingDuration: "0:21", receivedDate: "13 Feb 2024" },
      { id: "K017", name: "Kwabena Bediako", received: true, voiceRecordingDuration: "0:35", receivedDate: "13 Feb 2024" },
      { id: "K018", name: "Adjoa Agyei",     received: true, voiceRecordingDuration: "0:28", receivedDate: "13 Feb 2024" },
      { id: "K019", name: "Kofi Opoku",      received: true, voiceRecordingDuration: "0:39", receivedDate: "13 Feb 2024" },
      { id: "K020", name: "Esi Adusei",      received: true, voiceRecordingDuration: "0:26", receivedDate: "14 Feb 2024" },
      { id: "K021", name: "Kwame Kwarteng",  received: true, voiceRecordingDuration: "0:33", receivedDate: "14 Feb 2024" },
    ],
  },

  // ── Cash Opt-Outs ───────────────────────────────────────────────────────
  {
    id: "FS-2024-011",
    groupName: "Metro Pioneer Group",
    community: "Tamale Metro",
    agent: "Akosua Frimpong",
    disbursedDate: "02 Feb 2024",
    transactionId: "TXN-1A2B3C4D",
    disbursedAmount: 2640,
    approvedAmountPerFarmer: 120,
    approvedSupportType: "Cash",
    fulfillmentStage: "opted_out",
    momoNumber: "0244-777-888",
    momoName: "Metro Pioneer",
    confirmedFarmers: [
      { id: "MP001", name: "Kofi Agyeman",  received: true,  voiceRecordingDuration: "0:29", receivedDate: "05 Feb 2024" },
      { id: "MP002", name: "Ama Owusu",     received: true,  voiceRecordingDuration: "0:33", receivedDate: "05 Feb 2024" },
      { id: "MP003", name: "Yaw Asante",    received: true,  voiceRecordingDuration: "0:21", receivedDate: "05 Feb 2024" },
      { id: "MP004", name: "Abena Mensah",  received: false },
      { id: "MP005", name: "Kwame Darko",   received: false },
    ],
    optedOutFarmers: [
      { id: "OPT-MP-001", name: "Rabi Alhassan" },
      { id: "OPT-MP-002", name: "Sana Korawuni" },
      { id: "OPT-MP-003", name: "Azuma Atta" },
      { id: "OPT-MP-004", name: "Doapok Tidow" },
      { id: "OPT-MP-005", name: "Mercy Bakanyin" },
    ],
  },
  {
    id: "FS-2024-012",
    groupName: "Bole United Farmers",
    community: "Bole",
    agent: "Yaw Darko",
    disbursedDate: "05 Feb 2024",
    transactionId: "TXN-5E6F7G8H",
    disbursedAmount: 4200,
    approvedAmountPerFarmer: 150,
    approvedSupportType: "Cash",
    fulfillmentStage: "opted_out",
    momoNumber: "0551-444-555",
    momoName: "Bole United",
    confirmedFarmers: [
      { id: "BU001", name: "Issaka Wumbei",  received: true,  voiceRecordingDuration: "0:26", receivedDate: "08 Feb 2024" },
      { id: "BU002", name: "Fatima Konlan",  received: true,  voiceRecordingDuration: "0:34", receivedDate: "08 Feb 2024" },
      { id: "BU003", name: "Alhassan Bole",  received: false },
    ],
    optedOutFarmers: [
      { id: "OPT-BU-001", name: "Kusohuba Duku" },
      { id: "OPT-BU-002", name: "Shetu Affuro" },
      { id: "OPT-BU-003", name: "Yetama Akuta" },
    ],
  },
];
