// ---------------------------------------------------------------------------
// Mock data — replace with real API calls when connecting a backend
// ---------------------------------------------------------------------------
import type { FarmerRequest } from "./types";

export const MOCK_REQUESTS: FarmerRequest[] = [
  {
    id: "FS-2024-001", date: "12 Jan 2024", agent: "Kofi Mensah", community: "Tamale Metro",
    groupName: "Savannah Growers Union", score: null, stage: "synced", farmers: 22,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: null,
    groupScore: 65,
    farmersList: [
      { id: "FRM-0011", name: "Abena Owusu" },
      { id: "FRM-0012", name: "Kweku Asante" },
      { id: "FRM-0013", name: "Adwoa Mensah" },
      { id: "FRM-0014", name: "Kofi Adu" },
      { id: "FRM-0015", name: "Akosua Baidoo" },
      { id: "FRM-0016", name: "Yaw Appiah" },
      { id: "FRM-0017", name: "Efua Darko" },
      { id: "FRM-0018", name: "Nana Boateng" },
    ],
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0244-567-890", momoName: "Savannah Union GH" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.5 },
    ],
  },
  {
    id: "FS-2024-002", date: "15 Jan 2024", agent: "Ama Owusu", community: "Sawla-Tuna-Kalba",
    groupName: "Northern Fields Cooperative", score: null, stage: "synced", farmers: 18,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: null,
    hasFinancialRecords: true,
    groupScore: 48,
    farmersList: [
      { id: "FRM-0021", name: "Issaka Mahama" },
      { id: "FRM-0022", name: "Ramatu Abubakari" },
      { id: "FRM-0023", name: "Sumaila Seidu" },
      { id: "FRM-0024", name: "Fatima Yakubu" },
      { id: "FRM-0025", name: "Alhassan Fuseini" },
      { id: "FRM-0026", name: "Zenabu Dauda" },
    ],
    supportInterests: [
      { rank: "Primary",   type: "Ploughing", landSizePerFarmer: 2.0 },
      { rank: "Secondary", type: "Cash",      amountPerFarmer: 100, momoNumber: "0200-123-456", momoName: "Northern Coop" },
    ],
  },
  {
    id: "FS-2024-013", date: "08 Feb 2024", agent: "Kofi Mensah", community: "Nkoranza",
    groupName: "Nkoranza Double Yield Group", score: 72, stage: "pending_approval", farmers: 18,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: null,
    wantsDouble: true,
    supportInterests: [
      { rank: "Primary", type: "Cash", amountPerFarmer: 120, momoNumber: "0244-321-654", momoName: "Nkoranza DY Group" },
    ],
  },
  {
    id: "FS-2024-003", date: "18 Jan 2024", agent: "Yaw Darko", community: "Bole",
    groupName: "Bole Farmers Alliance", score: 62, stage: "pending_approval", farmers: 14,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: null,
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 150, momoNumber: "0551-234-567", momoName: "Bole Alliance" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.0 },
    ],
  },
  {
    id: "FS-2024-004", date: "20 Jan 2024", agent: "Abena Asante", community: "Wa East",
    groupName: "Wa East Crop Circle", score: 78, stage: "pending_approval", farmers: 31,
    onHold: true, holdComment: "MoMo account details need verification from field.", rejectionComment: "", approvedSupportType: null,
    supportInterests: [
      { rank: "Primary",   type: "Ploughing", landSizePerFarmer: 3.0 },
      { rank: "Secondary", type: "Cash",      amountPerFarmer: 200, momoNumber: "0244-987-654", momoName: "WE Crop Circle" },
    ],
  },
  {
    id: "FS-2024-005", date: "10 Jan 2024", agent: "Kwame Boateng", community: "Tamale Metro",
    groupName: "Metro Harvest Group", score: 38, stage: "rejected", farmers: 9,
    onHold: false, holdComment: "", rejectionComment: "Score too low to meet minimum eligibility threshold of 50.", approvedSupportType: null,
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 80,  momoNumber: "0200-000-001", momoName: "Metro Harvest" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 0.5 },
    ],
  },
  {
    id: "FS-2024-006", date: "22 Jan 2024", agent: "Efua Nkrumah", community: "Sawla-Tuna-Kalba",
    groupName: "Kalba Green Initiative", score: 84, stage: "agent_confirmation", farmers: 27,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0244-111-222", momoName: "Kalba Green" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.5 },
    ],
  },
  {
    id: "FS-2024-007", date: "25 Jan 2024", agent: "Nana Adjei", community: "Bole",
    groupName: "Bole Plough Collective", score: 91, stage: "finance_disbursement", farmers: 16,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedLandSizePerFarmer: 2.0,
    momoNumber: "0551-777-888", momoName: "Bole Collective",
    supportInterests: [
      { rank: "Primary",   type: "Ploughing", landSizePerFarmer: 2.0 },
      { rank: "Secondary", type: "Cash",      amountPerFarmer: 180, momoNumber: "0551-777-888", momoName: "Bole Collective" },
    ],
  },
  {
    id: "FS-2024-009", date: "26 Jan 2024", agent: "Kofi Mensah", community: "Tamale Metro",
    groupName: "Tamale Pioneer Farmers", score: 75, stage: "finance_disbursement", farmers: 20,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 150,
    momoNumber: "0244-333-444", momoName: "Tamale Pioneer",
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 150, momoNumber: "0244-333-444", momoName: "Tamale Pioneer" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.2 },
    ],
  },
  {
    id: "FS-2024-008", date: "30 Jan 2024", agent: "Akosua Frimpong", community: "Tamale Metro",
    groupName: "Metro Food Security Group", score: 88, stage: "disbursed", farmers: 34,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0244-555-666", momoName: "Metro Food Security",
    transactionId: "TXN-4F8A2B1C", disbursedAmount: 4080, disbursedDate: "30 Jan 2024",
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0244-555-666", momoName: "Metro Food Security" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.0 },
    ],
  },
  {
    id: "FS-2024-010", date: "28 Jan 2024", agent: "Ama Owusu", community: "Wa East",
    groupName: "Wa East Food Coalition", score: 95, stage: "disbursed", farmers: 40,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 180,
    momoNumber: "0244-999-000", momoName: "WE Food Coalition",
    transactionId: "TXN-7C3D9E2A", disbursedAmount: 7200, disbursedDate: "28 Jan 2024",
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 180, momoNumber: "0244-999-000", momoName: "WE Food Coalition" },
    ],
  },
  {
    id: "FS-2024-014", date: "01 Feb 2024", agent: "Yaw Darko", community: "Nanumba North",
    groupName: "Nanumba Agri Group", score: 80, stage: "disbursed", farmers: 19,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 150,
    momoNumber: "0246-601-432", momoName: "Nanumba Agri Group",
    transactionId: "TXN-2B4E6A8C", disbursedAmount: 2850, disbursedDate: "01 Feb 2024",
    supportInterests: [
      { rank: "Primary", type: "Cash", amountPerFarmer: 150, momoNumber: "0246-601-432", momoName: "Nanumba Agri Group" },
    ],
  },
  {
    id: "FS-2024-015", date: "03 Feb 2024", agent: "Nana Adjei", community: "Tolon",
    groupName: "Tolon Cooperative Society", score: 87, stage: "disbursed", farmers: 28,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0551-882-015", momoName: "Tolon Coop Society",
    transactionId: "TXN-9D1F3H5J", disbursedAmount: 3360, disbursedDate: "03 Feb 2024",
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0551-882-015", momoName: "Tolon Coop Society" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.5 },
    ],
  },
  {
    id: "FS-2024-011", date: "02 Feb 2024", agent: "Akosua Frimpong", community: "Tamale Metro",
    groupName: "Metro Pioneer Group", score: 80, stage: "opted_out", farmers: 25,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0244-777-888", momoName: "Metro Pioneer",
    transactionId: "TXN-1A2B3C4D", disbursedAmount: 2640, disbursedDate: "02 Feb 2024",
    optedOutFarmers: ["Rabi Alhassan", "Sana Korawuni", "Azuma Atta", "Doapok Tidow", "Mercy Bakanyin"],
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 120, momoNumber: "0244-777-888", momoName: "Metro Pioneer" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.0 },
    ],
  },
  {
    id: "FS-2024-012", date: "05 Feb 2024", agent: "Yaw Darko", community: "Bole",
    groupName: "Bole United Farmers", score: 88, stage: "opted_out", farmers: 30,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 150,
    momoNumber: "0551-444-555", momoName: "Bole United",
    transactionId: "TXN-5E6F7G8H", disbursedAmount: 4200, disbursedDate: "05 Feb 2024",
    optedOutFarmers: ["Kusohuba Duku", "Shetu Affuro", "Yetama Akuta"],
    supportInterests: [
      { rank: "Primary",   type: "Cash",      amountPerFarmer: 150, momoNumber: "0551-444-555", momoName: "Bole United" },
      { rank: "Secondary", type: "Ploughing", landSizePerFarmer: 1.5 },
    ],
  },

  // ── Extra disbursed records (for table pagination) ──────────────────────
  {
    id: "FS-2024-016", date: "06 Feb 2024", agent: "Kofi Mensah", community: "Kumbungu",
    groupName: "Kumbungu Crop Growers", score: 74, stage: "disbursed", farmers: 21,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 130,
    momoNumber: "0244-101-202", momoName: "Kumbungu Crop Growers",
    transactionId: "TXN-A1B2C3D4", disbursedAmount: 2730, disbursedDate: "06 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 130, momoNumber: "0244-101-202", momoName: "Kumbungu Crop Growers" }],
  },
  {
    id: "FS-2024-017", date: "07 Feb 2024", agent: "Ama Owusu", community: "Savelugu",
    groupName: "Savelugu Women Farmers", score: 83, stage: "disbursed", farmers: 16,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 150,
    momoNumber: "0200-303-404", momoName: "Savelugu Women Farmers",
    transactionId: "TXN-E5F6G7H8", disbursedAmount: 2400, disbursedDate: "07 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 150, momoNumber: "0200-303-404", momoName: "Savelugu Women Farmers" }],
  },
  {
    id: "FS-2024-018", date: "08 Feb 2024", agent: "Yaw Darko", community: "Karaga",
    groupName: "Karaga Seedlings Collective", score: 69, stage: "disbursed", farmers: 12,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedAmountPerFarmer: null,
    approvedLandSizePerFarmer: 2.0,
    momoNumber: "0551-505-606", momoName: "Karaga Seedlings",
    transactionId: "TXN-I9J0K1L2", disbursedAmount: 1560, disbursedDate: "08 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Ploughing", landSizePerFarmer: 2.0 }],
  },
  {
    id: "FS-2024-019", date: "09 Feb 2024", agent: "Nana Adjei", community: "Zabzugu",
    groupName: "Zabzugu Agri Pioneers", score: 91, stage: "disbursed", farmers: 37,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 200,
    momoNumber: "0244-707-808", momoName: "Zabzugu Agri Pioneers",
    transactionId: "TXN-M3N4O5P6", disbursedAmount: 7400, disbursedDate: "09 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 200, momoNumber: "0244-707-808", momoName: "Zabzugu Agri Pioneers" }],
  },
  {
    id: "FS-2024-020", date: "10 Feb 2024", agent: "Akosua Frimpong", community: "Gushegu",
    groupName: "Gushegu Yield Alliance", score: 78, stage: "disbursed", farmers: 29,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 110,
    momoNumber: "0246-909-010", momoName: "Gushegu Yield Alliance",
    transactionId: "TXN-Q7R8S9T0", disbursedAmount: 3190, disbursedDate: "10 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 110, momoNumber: "0246-909-010", momoName: "Gushegu Yield Alliance" }],
  },
  {
    id: "FS-2024-021", date: "11 Feb 2024", agent: "Kofi Mensah", community: "Nanton",
    groupName: "Nanton Food Bank Growers", score: 85, stage: "disbursed", farmers: 23,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 140,
    momoNumber: "0244-111-222", momoName: "Nanton Food Bank",
    transactionId: "TXN-U1V2W3X4", disbursedAmount: 3220, disbursedDate: "11 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 140, momoNumber: "0244-111-222", momoName: "Nanton Food Bank" }],
  },
  {
    id: "FS-2024-022", date: "12 Feb 2024", agent: "Ama Owusu", community: "Mion",
    groupName: "Mion Cooperative Farmers", score: 66, stage: "disbursed", farmers: 18,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedAmountPerFarmer: null,
    approvedLandSizePerFarmer: 1.5,
    momoNumber: "0200-333-444", momoName: "Mion Coop Farmers",
    transactionId: "TXN-Y5Z6A7B8", disbursedAmount: 1800, disbursedDate: "12 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Ploughing", landSizePerFarmer: 1.5 }],
  },
  {
    id: "FS-2024-023", date: "13 Feb 2024", agent: "Yaw Darko", community: "Chereponi",
    groupName: "Chereponi Upland Farmers", score: 72, stage: "disbursed", farmers: 15,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0551-555-666", momoName: "Chereponi Upland",
    transactionId: "TXN-C9D0E1F2", disbursedAmount: 1800, disbursedDate: "13 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 120, momoNumber: "0551-555-666", momoName: "Chereponi Upland" }],
  },
  {
    id: "FS-2024-024", date: "14 Feb 2024", agent: "Nana Adjei", community: "Bunkpurugu",
    groupName: "Bunkpurugu Harvest Group", score: 89, stage: "disbursed", farmers: 32,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 160,
    momoNumber: "0244-777-888", momoName: "Bunkpurugu Harvest",
    transactionId: "TXN-G3H4I5J6", disbursedAmount: 5120, disbursedDate: "14 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 160, momoNumber: "0244-777-888", momoName: "Bunkpurugu Harvest" }],
  },
  {
    id: "FS-2024-025", date: "15 Feb 2024", agent: "Akosua Frimpong", community: "Yunyoo",
    groupName: "Yunyoo Valley Growers", score: 77, stage: "disbursed", farmers: 20,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 175,
    momoNumber: "0246-999-000", momoName: "Yunyoo Valley Growers",
    transactionId: "TXN-K7L8M9N0", disbursedAmount: 3500, disbursedDate: "15 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 175, momoNumber: "0246-999-000", momoName: "Yunyoo Valley Growers" }],
  },
  {
    id: "FS-2024-026", date: "16 Feb 2024", agent: "Kofi Mensah", community: "Tatale-Sanguli",
    groupName: "Tatale Organic Farmers", score: 82, stage: "disbursed", farmers: 26,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 130,
    momoNumber: "0244-121-131", momoName: "Tatale Organic Farmers",
    transactionId: "TXN-O1P2Q3R4", disbursedAmount: 3380, disbursedDate: "16 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 130, momoNumber: "0244-121-131", momoName: "Tatale Organic Farmers" }],
  },
  {
    id: "FS-2024-027", date: "17 Feb 2024", agent: "Ama Owusu", community: "Walewale",
    groupName: "Walewale Grain Collective", score: 93, stage: "disbursed", farmers: 45,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 190,
    momoNumber: "0200-141-151", momoName: "Walewale Grain Collective",
    transactionId: "TXN-S5T6U7V8", disbursedAmount: 8550, disbursedDate: "17 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 190, momoNumber: "0200-141-151", momoName: "Walewale Grain Collective" }],
  },
  {
    id: "FS-2024-028", date: "18 Feb 2024", agent: "Yaw Darko", community: "Builsa North",
    groupName: "Builsa North Farmers Union", score: 70, stage: "disbursed", farmers: 22,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedAmountPerFarmer: null,
    approvedLandSizePerFarmer: 1.8,
    momoNumber: "0551-161-171", momoName: "Builsa North Union",
    transactionId: "TXN-W9X0Y1Z2", disbursedAmount: 2640, disbursedDate: "18 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Ploughing", landSizePerFarmer: 1.8 }],
  },
  {
    id: "FS-2024-029", date: "19 Feb 2024", agent: "Nana Adjei", community: "Kasena-Nankana",
    groupName: "Kasena Irrigation Collective", score: 86, stage: "disbursed", farmers: 31,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 145,
    momoNumber: "0244-181-191", momoName: "Kasena Irrigation Collective",
    transactionId: "TXN-A3B4C5D6", disbursedAmount: 4495, disbursedDate: "19 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 145, momoNumber: "0244-181-191", momoName: "Kasena Irrigation Collective" }],
  },
  {
    id: "FS-2024-030", date: "20 Feb 2024", agent: "Akosua Frimpong", community: "Sissala East",
    groupName: "Sissala Dryland Farmers", score: 75, stage: "disbursed", farmers: 17,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 120,
    momoNumber: "0246-201-211", momoName: "Sissala Dryland Farmers",
    transactionId: "TXN-E7F8G9H0", disbursedAmount: 2040, disbursedDate: "20 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 120, momoNumber: "0246-201-211", momoName: "Sissala Dryland Farmers" }],
  },
  {
    id: "FS-2024-031", date: "21 Feb 2024", agent: "Kofi Mensah", community: "Jirapa",
    groupName: "Jirapa Hills Cooperative", score: 88, stage: "disbursed", farmers: 38,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 155,
    momoNumber: "0244-221-231", momoName: "Jirapa Hills Cooperative",
    transactionId: "TXN-I1J2K3L4", disbursedAmount: 5890, disbursedDate: "21 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 155, momoNumber: "0244-221-231", momoName: "Jirapa Hills Cooperative" }],
  },
  {
    id: "FS-2024-032", date: "22 Feb 2024", agent: "Ama Owusu", community: "Lawra",
    groupName: "Lawra River Farmers", score: 79, stage: "disbursed", farmers: 24,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 135,
    momoNumber: "0200-241-251", momoName: "Lawra River Farmers",
    transactionId: "TXN-M5N6O7P8", disbursedAmount: 3240, disbursedDate: "22 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 135, momoNumber: "0200-241-251", momoName: "Lawra River Farmers" }],
  },
  {
    id: "FS-2024-033", date: "23 Feb 2024", agent: "Yaw Darko", community: "Nandom",
    groupName: "Nandom Plateau Growers", score: 81, stage: "disbursed", farmers: 27,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Ploughing",
    approvedAmountPerFarmer: null,
    approvedLandSizePerFarmer: 2.2,
    momoNumber: "0551-261-271", momoName: "Nandom Plateau Growers",
    transactionId: "TXN-Q9R0S1T2", disbursedAmount: 3510, disbursedDate: "23 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Ploughing", landSizePerFarmer: 2.2 }],
  },
  {
    id: "FS-2024-034", date: "24 Feb 2024", agent: "Nana Adjei", community: "Daffiama-Bussie",
    groupName: "Daffiama United Growers", score: 90, stage: "disbursed", farmers: 33,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 170,
    momoNumber: "0244-281-291", momoName: "Daffiama United Growers",
    transactionId: "TXN-U3V4W5X6", disbursedAmount: 5610, disbursedDate: "24 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 170, momoNumber: "0244-281-291", momoName: "Daffiama United Growers" }],
  },
  {
    id: "FS-2024-035", date: "25 Feb 2024", agent: "Akosua Frimpong", community: "Nadowli-Kaleo",
    groupName: "Kaleo Lowland Farmers", score: 73, stage: "disbursed", farmers: 19,
    onHold: false, holdComment: "", rejectionComment: "", approvedSupportType: "Cash",
    approvedAmountPerFarmer: 125,
    momoNumber: "0246-301-311", momoName: "Kaleo Lowland Farmers",
    transactionId: "TXN-Y7Z8A9B0", disbursedAmount: 2375, disbursedDate: "25 Feb 2024",
    supportInterests: [{ rank: "Primary", type: "Cash", amountPerFarmer: 125, momoNumber: "0246-301-311", momoName: "Kaleo Lowland Farmers" }],
  },
];
